// Code generated by entc, DO NOT EDIT.

package ent

import "context"

func (s *Stocks) Stocks(ctx context.Context) ([]*Stocks, error) {
	result, err := s.Edges.StocksOrErr()
	if IsNotLoaded(err) {
		result, err = s.QueryStocks().All(ctx)
	}
	return result, err
}
