version: '3.7'
services:
    postgres:
        image: postgres:latest
        restart: always
        environment:
          - TZ=Asia/Tokyo
          - POSTGRES_DB=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes:
          - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          # - ./migrations:/docker-entrypoint-initdb.d
