// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"github.com/gushikem01/usa-kabu-go/ent/predicate"
	"github.com/gushikem01/usa-kabu-go/ent/stocks"

	"entgo.io/ent"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeStocks = "Stocks"
)

// StocksMutation represents an operation that mutates the Stocks nodes in the graph.
type StocksMutation struct {
	config
	op                  Op
	typ                 string
	id                  *int
	symbol              *string
	name_ja             *string
	_type               *string
	exchange            *string
	exchange_short_name *string
	price               *float64
	addprice            *float64
	created_at          *time.Time
	updated_at          *time.Time
	clearedFields       map[string]struct{}
	stocks              map[int]struct{}
	removedstocks       map[int]struct{}
	clearedstocks       bool
	done                bool
	oldValue            func(context.Context) (*Stocks, error)
	predicates          []predicate.Stocks
}

var _ ent.Mutation = (*StocksMutation)(nil)

// stocksOption allows management of the mutation configuration using functional options.
type stocksOption func(*StocksMutation)

// newStocksMutation creates new mutation for the Stocks entity.
func newStocksMutation(c config, op Op, opts ...stocksOption) *StocksMutation {
	m := &StocksMutation{
		config:        c,
		op:            op,
		typ:           TypeStocks,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withStocksID sets the ID field of the mutation.
func withStocksID(id int) stocksOption {
	return func(m *StocksMutation) {
		var (
			err   error
			once  sync.Once
			value *Stocks
		)
		m.oldValue = func(ctx context.Context) (*Stocks, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Stocks.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withStocks sets the old Stocks of the mutation.
func withStocks(node *Stocks) stocksOption {
	return func(m *StocksMutation) {
		m.oldValue = func(context.Context) (*Stocks, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m StocksMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m StocksMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *StocksMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *StocksMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Stocks.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetSymbol sets the "symbol" field.
func (m *StocksMutation) SetSymbol(s string) {
	m.symbol = &s
}

// Symbol returns the value of the "symbol" field in the mutation.
func (m *StocksMutation) Symbol() (r string, exists bool) {
	v := m.symbol
	if v == nil {
		return
	}
	return *v, true
}

// OldSymbol returns the old "symbol" field's value of the Stocks entity.
// If the Stocks object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StocksMutation) OldSymbol(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSymbol is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSymbol requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSymbol: %w", err)
	}
	return oldValue.Symbol, nil
}

// ResetSymbol resets all changes to the "symbol" field.
func (m *StocksMutation) ResetSymbol() {
	m.symbol = nil
}

// SetNameJa sets the "name_ja" field.
func (m *StocksMutation) SetNameJa(s string) {
	m.name_ja = &s
}

// NameJa returns the value of the "name_ja" field in the mutation.
func (m *StocksMutation) NameJa() (r string, exists bool) {
	v := m.name_ja
	if v == nil {
		return
	}
	return *v, true
}

// OldNameJa returns the old "name_ja" field's value of the Stocks entity.
// If the Stocks object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StocksMutation) OldNameJa(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNameJa is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNameJa requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNameJa: %w", err)
	}
	return oldValue.NameJa, nil
}

// ClearNameJa clears the value of the "name_ja" field.
func (m *StocksMutation) ClearNameJa() {
	m.name_ja = nil
	m.clearedFields[stocks.FieldNameJa] = struct{}{}
}

// NameJaCleared returns if the "name_ja" field was cleared in this mutation.
func (m *StocksMutation) NameJaCleared() bool {
	_, ok := m.clearedFields[stocks.FieldNameJa]
	return ok
}

// ResetNameJa resets all changes to the "name_ja" field.
func (m *StocksMutation) ResetNameJa() {
	m.name_ja = nil
	delete(m.clearedFields, stocks.FieldNameJa)
}

// SetType sets the "type" field.
func (m *StocksMutation) SetType(s string) {
	m._type = &s
}

// GetType returns the value of the "type" field in the mutation.
func (m *StocksMutation) GetType() (r string, exists bool) {
	v := m._type
	if v == nil {
		return
	}
	return *v, true
}

// OldType returns the old "type" field's value of the Stocks entity.
// If the Stocks object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StocksMutation) OldType(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldType: %w", err)
	}
	return oldValue.Type, nil
}

// ResetType resets all changes to the "type" field.
func (m *StocksMutation) ResetType() {
	m._type = nil
}

// SetExchange sets the "exchange" field.
func (m *StocksMutation) SetExchange(s string) {
	m.exchange = &s
}

// Exchange returns the value of the "exchange" field in the mutation.
func (m *StocksMutation) Exchange() (r string, exists bool) {
	v := m.exchange
	if v == nil {
		return
	}
	return *v, true
}

// OldExchange returns the old "exchange" field's value of the Stocks entity.
// If the Stocks object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StocksMutation) OldExchange(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldExchange is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldExchange requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldExchange: %w", err)
	}
	return oldValue.Exchange, nil
}

// ResetExchange resets all changes to the "exchange" field.
func (m *StocksMutation) ResetExchange() {
	m.exchange = nil
}

// SetExchangeShortName sets the "exchange_short_name" field.
func (m *StocksMutation) SetExchangeShortName(s string) {
	m.exchange_short_name = &s
}

// ExchangeShortName returns the value of the "exchange_short_name" field in the mutation.
func (m *StocksMutation) ExchangeShortName() (r string, exists bool) {
	v := m.exchange_short_name
	if v == nil {
		return
	}
	return *v, true
}

// OldExchangeShortName returns the old "exchange_short_name" field's value of the Stocks entity.
// If the Stocks object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StocksMutation) OldExchangeShortName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldExchangeShortName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldExchangeShortName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldExchangeShortName: %w", err)
	}
	return oldValue.ExchangeShortName, nil
}

// ResetExchangeShortName resets all changes to the "exchange_short_name" field.
func (m *StocksMutation) ResetExchangeShortName() {
	m.exchange_short_name = nil
}

// SetPrice sets the "price" field.
func (m *StocksMutation) SetPrice(f float64) {
	m.price = &f
	m.addprice = nil
}

// Price returns the value of the "price" field in the mutation.
func (m *StocksMutation) Price() (r float64, exists bool) {
	v := m.price
	if v == nil {
		return
	}
	return *v, true
}

// OldPrice returns the old "price" field's value of the Stocks entity.
// If the Stocks object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StocksMutation) OldPrice(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPrice is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPrice requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPrice: %w", err)
	}
	return oldValue.Price, nil
}

// AddPrice adds f to the "price" field.
func (m *StocksMutation) AddPrice(f float64) {
	if m.addprice != nil {
		*m.addprice += f
	} else {
		m.addprice = &f
	}
}

// AddedPrice returns the value that was added to the "price" field in this mutation.
func (m *StocksMutation) AddedPrice() (r float64, exists bool) {
	v := m.addprice
	if v == nil {
		return
	}
	return *v, true
}

// ResetPrice resets all changes to the "price" field.
func (m *StocksMutation) ResetPrice() {
	m.price = nil
	m.addprice = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *StocksMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *StocksMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Stocks entity.
// If the Stocks object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StocksMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *StocksMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *StocksMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *StocksMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Stocks entity.
// If the Stocks object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StocksMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *StocksMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// AddStockIDs adds the "stocks" edge to the Stocks entity by ids.
func (m *StocksMutation) AddStockIDs(ids ...int) {
	if m.stocks == nil {
		m.stocks = make(map[int]struct{})
	}
	for i := range ids {
		m.stocks[ids[i]] = struct{}{}
	}
}

// ClearStocks clears the "stocks" edge to the Stocks entity.
func (m *StocksMutation) ClearStocks() {
	m.clearedstocks = true
}

// StocksCleared reports if the "stocks" edge to the Stocks entity was cleared.
func (m *StocksMutation) StocksCleared() bool {
	return m.clearedstocks
}

// RemoveStockIDs removes the "stocks" edge to the Stocks entity by IDs.
func (m *StocksMutation) RemoveStockIDs(ids ...int) {
	if m.removedstocks == nil {
		m.removedstocks = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.stocks, ids[i])
		m.removedstocks[ids[i]] = struct{}{}
	}
}

// RemovedStocks returns the removed IDs of the "stocks" edge to the Stocks entity.
func (m *StocksMutation) RemovedStocksIDs() (ids []int) {
	for id := range m.removedstocks {
		ids = append(ids, id)
	}
	return
}

// StocksIDs returns the "stocks" edge IDs in the mutation.
func (m *StocksMutation) StocksIDs() (ids []int) {
	for id := range m.stocks {
		ids = append(ids, id)
	}
	return
}

// ResetStocks resets all changes to the "stocks" edge.
func (m *StocksMutation) ResetStocks() {
	m.stocks = nil
	m.clearedstocks = false
	m.removedstocks = nil
}

// Where appends a list predicates to the StocksMutation builder.
func (m *StocksMutation) Where(ps ...predicate.Stocks) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *StocksMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (Stocks).
func (m *StocksMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *StocksMutation) Fields() []string {
	fields := make([]string, 0, 8)
	if m.symbol != nil {
		fields = append(fields, stocks.FieldSymbol)
	}
	if m.name_ja != nil {
		fields = append(fields, stocks.FieldNameJa)
	}
	if m._type != nil {
		fields = append(fields, stocks.FieldType)
	}
	if m.exchange != nil {
		fields = append(fields, stocks.FieldExchange)
	}
	if m.exchange_short_name != nil {
		fields = append(fields, stocks.FieldExchangeShortName)
	}
	if m.price != nil {
		fields = append(fields, stocks.FieldPrice)
	}
	if m.created_at != nil {
		fields = append(fields, stocks.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, stocks.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *StocksMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case stocks.FieldSymbol:
		return m.Symbol()
	case stocks.FieldNameJa:
		return m.NameJa()
	case stocks.FieldType:
		return m.GetType()
	case stocks.FieldExchange:
		return m.Exchange()
	case stocks.FieldExchangeShortName:
		return m.ExchangeShortName()
	case stocks.FieldPrice:
		return m.Price()
	case stocks.FieldCreatedAt:
		return m.CreatedAt()
	case stocks.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *StocksMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case stocks.FieldSymbol:
		return m.OldSymbol(ctx)
	case stocks.FieldNameJa:
		return m.OldNameJa(ctx)
	case stocks.FieldType:
		return m.OldType(ctx)
	case stocks.FieldExchange:
		return m.OldExchange(ctx)
	case stocks.FieldExchangeShortName:
		return m.OldExchangeShortName(ctx)
	case stocks.FieldPrice:
		return m.OldPrice(ctx)
	case stocks.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case stocks.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Stocks field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *StocksMutation) SetField(name string, value ent.Value) error {
	switch name {
	case stocks.FieldSymbol:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSymbol(v)
		return nil
	case stocks.FieldNameJa:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNameJa(v)
		return nil
	case stocks.FieldType:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetType(v)
		return nil
	case stocks.FieldExchange:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetExchange(v)
		return nil
	case stocks.FieldExchangeShortName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetExchangeShortName(v)
		return nil
	case stocks.FieldPrice:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPrice(v)
		return nil
	case stocks.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case stocks.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Stocks field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *StocksMutation) AddedFields() []string {
	var fields []string
	if m.addprice != nil {
		fields = append(fields, stocks.FieldPrice)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *StocksMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case stocks.FieldPrice:
		return m.AddedPrice()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *StocksMutation) AddField(name string, value ent.Value) error {
	switch name {
	case stocks.FieldPrice:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddPrice(v)
		return nil
	}
	return fmt.Errorf("unknown Stocks numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *StocksMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(stocks.FieldNameJa) {
		fields = append(fields, stocks.FieldNameJa)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *StocksMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *StocksMutation) ClearField(name string) error {
	switch name {
	case stocks.FieldNameJa:
		m.ClearNameJa()
		return nil
	}
	return fmt.Errorf("unknown Stocks nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *StocksMutation) ResetField(name string) error {
	switch name {
	case stocks.FieldSymbol:
		m.ResetSymbol()
		return nil
	case stocks.FieldNameJa:
		m.ResetNameJa()
		return nil
	case stocks.FieldType:
		m.ResetType()
		return nil
	case stocks.FieldExchange:
		m.ResetExchange()
		return nil
	case stocks.FieldExchangeShortName:
		m.ResetExchangeShortName()
		return nil
	case stocks.FieldPrice:
		m.ResetPrice()
		return nil
	case stocks.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case stocks.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown Stocks field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *StocksMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.stocks != nil {
		edges = append(edges, stocks.EdgeStocks)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *StocksMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case stocks.EdgeStocks:
		ids := make([]ent.Value, 0, len(m.stocks))
		for id := range m.stocks {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *StocksMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedstocks != nil {
		edges = append(edges, stocks.EdgeStocks)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *StocksMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case stocks.EdgeStocks:
		ids := make([]ent.Value, 0, len(m.removedstocks))
		for id := range m.removedstocks {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *StocksMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedstocks {
		edges = append(edges, stocks.EdgeStocks)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *StocksMutation) EdgeCleared(name string) bool {
	switch name {
	case stocks.EdgeStocks:
		return m.clearedstocks
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *StocksMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Stocks unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *StocksMutation) ResetEdge(name string) error {
	switch name {
	case stocks.EdgeStocks:
		m.ResetStocks()
		return nil
	}
	return fmt.Errorf("unknown Stocks edge %s", name)
}
