// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/gushikem01/usa-kabu-go/ent/schema"
	"github.com/gushikem01/usa-kabu-go/ent/stocks"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	stocksFields := schema.Stocks{}.Fields()
	_ = stocksFields
	// stocksDescCreatedAt is the schema descriptor for created_at field.
	stocksDescCreatedAt := stocksFields[7].Descriptor()
	// stocks.DefaultCreatedAt holds the default value on creation for the created_at field.
	stocks.DefaultCreatedAt = stocksDescCreatedAt.Default.(func() time.Time)
	// stocksDescUpdatedAt is the schema descriptor for updated_at field.
	stocksDescUpdatedAt := stocksFields[8].Descriptor()
	// stocks.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	stocks.DefaultUpdatedAt = stocksDescUpdatedAt.Default.(func() time.Time)
}
