// Code generated by entc, DO NOT EDIT.

package stocks

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/gushikem01/usa-kabu-go/server/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Symbol applies equality check predicate on the "symbol" field. It's identical to SymbolEQ.
func Symbol(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSymbol), v))
	})
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldName), v))
	})
}

// NameJa applies equality check predicate on the "name_ja" field. It's identical to NameJaEQ.
func NameJa(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldNameJa), v))
	})
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldType), v))
	})
}

// Exchange applies equality check predicate on the "exchange" field. It's identical to ExchangeEQ.
func Exchange(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldExchange), v))
	})
}

// ExchangeShortName applies equality check predicate on the "exchange_short_name" field. It's identical to ExchangeShortNameEQ.
func ExchangeShortName(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldExchangeShortName), v))
	})
}

// Price applies equality check predicate on the "price" field. It's identical to PriceEQ.
func Price(v float64) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPrice), v))
	})
}

// Industry applies equality check predicate on the "industry" field. It's identical to IndustryEQ.
func Industry(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldIndustry), v))
	})
}

// MarketCarp applies equality check predicate on the "market_carp" field. It's identical to MarketCarpEQ.
func MarketCarp(v float64) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldMarketCarp), v))
	})
}

// LastDiv applies equality check predicate on the "last_div" field. It's identical to LastDivEQ.
func LastDiv(v float64) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLastDiv), v))
	})
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v float64) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDescription), v))
	})
}

// Website applies equality check predicate on the "website" field. It's identical to WebsiteEQ.
func Website(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldWebsite), v))
	})
}

// Ceo applies equality check predicate on the "ceo" field. It's identical to CeoEQ.
func Ceo(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCeo), v))
	})
}

// Sector applies equality check predicate on the "sector" field. It's identical to SectorEQ.
func Sector(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSector), v))
	})
}

// Country applies equality check predicate on the "country" field. It's identical to CountryEQ.
func Country(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCountry), v))
	})
}

// FullTimeEmployees applies equality check predicate on the "full_time_employees" field. It's identical to FullTimeEmployeesEQ.
func FullTimeEmployees(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldFullTimeEmployees), v))
	})
}

// Phone applies equality check predicate on the "phone" field. It's identical to PhoneEQ.
func Phone(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPhone), v))
	})
}

// Address applies equality check predicate on the "address" field. It's identical to AddressEQ.
func Address(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldAddress), v))
	})
}

// City applies equality check predicate on the "city" field. It's identical to CityEQ.
func City(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCity), v))
	})
}

// State applies equality check predicate on the "state" field. It's identical to StateEQ.
func State(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldState), v))
	})
}

// Zip applies equality check predicate on the "zip" field. It's identical to ZipEQ.
func Zip(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldZip), v))
	})
}

// Image applies equality check predicate on the "image" field. It's identical to ImageEQ.
func Image(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldImage), v))
	})
}

// IpoDate applies equality check predicate on the "ipo_date" field. It's identical to IpoDateEQ.
func IpoDate(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldIpoDate), v))
	})
}

// Yield applies equality check predicate on the "yield" field. It's identical to YieldEQ.
func Yield(v float64) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldYield), v))
	})
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// SymbolEQ applies the EQ predicate on the "symbol" field.
func SymbolEQ(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSymbol), v))
	})
}

// SymbolNEQ applies the NEQ predicate on the "symbol" field.
func SymbolNEQ(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSymbol), v))
	})
}

// SymbolIn applies the In predicate on the "symbol" field.
func SymbolIn(vs ...string) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldSymbol), v...))
	})
}

// SymbolNotIn applies the NotIn predicate on the "symbol" field.
func SymbolNotIn(vs ...string) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldSymbol), v...))
	})
}

// SymbolGT applies the GT predicate on the "symbol" field.
func SymbolGT(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldSymbol), v))
	})
}

// SymbolGTE applies the GTE predicate on the "symbol" field.
func SymbolGTE(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldSymbol), v))
	})
}

// SymbolLT applies the LT predicate on the "symbol" field.
func SymbolLT(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldSymbol), v))
	})
}

// SymbolLTE applies the LTE predicate on the "symbol" field.
func SymbolLTE(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldSymbol), v))
	})
}

// SymbolContains applies the Contains predicate on the "symbol" field.
func SymbolContains(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldSymbol), v))
	})
}

// SymbolHasPrefix applies the HasPrefix predicate on the "symbol" field.
func SymbolHasPrefix(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldSymbol), v))
	})
}

// SymbolHasSuffix applies the HasSuffix predicate on the "symbol" field.
func SymbolHasSuffix(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldSymbol), v))
	})
}

// SymbolIsNil applies the IsNil predicate on the "symbol" field.
func SymbolIsNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldSymbol)))
	})
}

// SymbolNotNil applies the NotNil predicate on the "symbol" field.
func SymbolNotNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldSymbol)))
	})
}

// SymbolEqualFold applies the EqualFold predicate on the "symbol" field.
func SymbolEqualFold(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldSymbol), v))
	})
}

// SymbolContainsFold applies the ContainsFold predicate on the "symbol" field.
func SymbolContainsFold(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldSymbol), v))
	})
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldName), v))
	})
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldName), v))
	})
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldName), v...))
	})
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldName), v...))
	})
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldName), v))
	})
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldName), v))
	})
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldName), v))
	})
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldName), v))
	})
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldName), v))
	})
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldName), v))
	})
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldName), v))
	})
}

// NameIsNil applies the IsNil predicate on the "name" field.
func NameIsNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldName)))
	})
}

// NameNotNil applies the NotNil predicate on the "name" field.
func NameNotNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldName)))
	})
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldName), v))
	})
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldName), v))
	})
}

// NameJaEQ applies the EQ predicate on the "name_ja" field.
func NameJaEQ(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldNameJa), v))
	})
}

// NameJaNEQ applies the NEQ predicate on the "name_ja" field.
func NameJaNEQ(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldNameJa), v))
	})
}

// NameJaIn applies the In predicate on the "name_ja" field.
func NameJaIn(vs ...string) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldNameJa), v...))
	})
}

// NameJaNotIn applies the NotIn predicate on the "name_ja" field.
func NameJaNotIn(vs ...string) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldNameJa), v...))
	})
}

// NameJaGT applies the GT predicate on the "name_ja" field.
func NameJaGT(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldNameJa), v))
	})
}

// NameJaGTE applies the GTE predicate on the "name_ja" field.
func NameJaGTE(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldNameJa), v))
	})
}

// NameJaLT applies the LT predicate on the "name_ja" field.
func NameJaLT(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldNameJa), v))
	})
}

// NameJaLTE applies the LTE predicate on the "name_ja" field.
func NameJaLTE(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldNameJa), v))
	})
}

// NameJaContains applies the Contains predicate on the "name_ja" field.
func NameJaContains(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldNameJa), v))
	})
}

// NameJaHasPrefix applies the HasPrefix predicate on the "name_ja" field.
func NameJaHasPrefix(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldNameJa), v))
	})
}

// NameJaHasSuffix applies the HasSuffix predicate on the "name_ja" field.
func NameJaHasSuffix(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldNameJa), v))
	})
}

// NameJaIsNil applies the IsNil predicate on the "name_ja" field.
func NameJaIsNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldNameJa)))
	})
}

// NameJaNotNil applies the NotNil predicate on the "name_ja" field.
func NameJaNotNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldNameJa)))
	})
}

// NameJaEqualFold applies the EqualFold predicate on the "name_ja" field.
func NameJaEqualFold(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldNameJa), v))
	})
}

// NameJaContainsFold applies the ContainsFold predicate on the "name_ja" field.
func NameJaContainsFold(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldNameJa), v))
	})
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldType), v))
	})
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldType), v))
	})
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldType), v...))
	})
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldType), v...))
	})
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldType), v))
	})
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldType), v))
	})
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldType), v))
	})
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldType), v))
	})
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldType), v))
	})
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldType), v))
	})
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldType), v))
	})
}

// TypeIsNil applies the IsNil predicate on the "type" field.
func TypeIsNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldType)))
	})
}

// TypeNotNil applies the NotNil predicate on the "type" field.
func TypeNotNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldType)))
	})
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldType), v))
	})
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldType), v))
	})
}

// ExchangeEQ applies the EQ predicate on the "exchange" field.
func ExchangeEQ(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldExchange), v))
	})
}

// ExchangeNEQ applies the NEQ predicate on the "exchange" field.
func ExchangeNEQ(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldExchange), v))
	})
}

// ExchangeIn applies the In predicate on the "exchange" field.
func ExchangeIn(vs ...string) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldExchange), v...))
	})
}

// ExchangeNotIn applies the NotIn predicate on the "exchange" field.
func ExchangeNotIn(vs ...string) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldExchange), v...))
	})
}

// ExchangeGT applies the GT predicate on the "exchange" field.
func ExchangeGT(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldExchange), v))
	})
}

// ExchangeGTE applies the GTE predicate on the "exchange" field.
func ExchangeGTE(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldExchange), v))
	})
}

// ExchangeLT applies the LT predicate on the "exchange" field.
func ExchangeLT(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldExchange), v))
	})
}

// ExchangeLTE applies the LTE predicate on the "exchange" field.
func ExchangeLTE(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldExchange), v))
	})
}

// ExchangeContains applies the Contains predicate on the "exchange" field.
func ExchangeContains(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldExchange), v))
	})
}

// ExchangeHasPrefix applies the HasPrefix predicate on the "exchange" field.
func ExchangeHasPrefix(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldExchange), v))
	})
}

// ExchangeHasSuffix applies the HasSuffix predicate on the "exchange" field.
func ExchangeHasSuffix(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldExchange), v))
	})
}

// ExchangeIsNil applies the IsNil predicate on the "exchange" field.
func ExchangeIsNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldExchange)))
	})
}

// ExchangeNotNil applies the NotNil predicate on the "exchange" field.
func ExchangeNotNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldExchange)))
	})
}

// ExchangeEqualFold applies the EqualFold predicate on the "exchange" field.
func ExchangeEqualFold(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldExchange), v))
	})
}

// ExchangeContainsFold applies the ContainsFold predicate on the "exchange" field.
func ExchangeContainsFold(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldExchange), v))
	})
}

// ExchangeShortNameEQ applies the EQ predicate on the "exchange_short_name" field.
func ExchangeShortNameEQ(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldExchangeShortName), v))
	})
}

// ExchangeShortNameNEQ applies the NEQ predicate on the "exchange_short_name" field.
func ExchangeShortNameNEQ(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldExchangeShortName), v))
	})
}

// ExchangeShortNameIn applies the In predicate on the "exchange_short_name" field.
func ExchangeShortNameIn(vs ...string) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldExchangeShortName), v...))
	})
}

// ExchangeShortNameNotIn applies the NotIn predicate on the "exchange_short_name" field.
func ExchangeShortNameNotIn(vs ...string) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldExchangeShortName), v...))
	})
}

// ExchangeShortNameGT applies the GT predicate on the "exchange_short_name" field.
func ExchangeShortNameGT(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldExchangeShortName), v))
	})
}

// ExchangeShortNameGTE applies the GTE predicate on the "exchange_short_name" field.
func ExchangeShortNameGTE(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldExchangeShortName), v))
	})
}

// ExchangeShortNameLT applies the LT predicate on the "exchange_short_name" field.
func ExchangeShortNameLT(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldExchangeShortName), v))
	})
}

// ExchangeShortNameLTE applies the LTE predicate on the "exchange_short_name" field.
func ExchangeShortNameLTE(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldExchangeShortName), v))
	})
}

// ExchangeShortNameContains applies the Contains predicate on the "exchange_short_name" field.
func ExchangeShortNameContains(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldExchangeShortName), v))
	})
}

// ExchangeShortNameHasPrefix applies the HasPrefix predicate on the "exchange_short_name" field.
func ExchangeShortNameHasPrefix(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldExchangeShortName), v))
	})
}

// ExchangeShortNameHasSuffix applies the HasSuffix predicate on the "exchange_short_name" field.
func ExchangeShortNameHasSuffix(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldExchangeShortName), v))
	})
}

// ExchangeShortNameIsNil applies the IsNil predicate on the "exchange_short_name" field.
func ExchangeShortNameIsNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldExchangeShortName)))
	})
}

// ExchangeShortNameNotNil applies the NotNil predicate on the "exchange_short_name" field.
func ExchangeShortNameNotNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldExchangeShortName)))
	})
}

// ExchangeShortNameEqualFold applies the EqualFold predicate on the "exchange_short_name" field.
func ExchangeShortNameEqualFold(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldExchangeShortName), v))
	})
}

// ExchangeShortNameContainsFold applies the ContainsFold predicate on the "exchange_short_name" field.
func ExchangeShortNameContainsFold(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldExchangeShortName), v))
	})
}

// PriceEQ applies the EQ predicate on the "price" field.
func PriceEQ(v float64) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPrice), v))
	})
}

// PriceNEQ applies the NEQ predicate on the "price" field.
func PriceNEQ(v float64) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldPrice), v))
	})
}

// PriceIn applies the In predicate on the "price" field.
func PriceIn(vs ...float64) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldPrice), v...))
	})
}

// PriceNotIn applies the NotIn predicate on the "price" field.
func PriceNotIn(vs ...float64) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldPrice), v...))
	})
}

// PriceGT applies the GT predicate on the "price" field.
func PriceGT(v float64) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldPrice), v))
	})
}

// PriceGTE applies the GTE predicate on the "price" field.
func PriceGTE(v float64) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldPrice), v))
	})
}

// PriceLT applies the LT predicate on the "price" field.
func PriceLT(v float64) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldPrice), v))
	})
}

// PriceLTE applies the LTE predicate on the "price" field.
func PriceLTE(v float64) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldPrice), v))
	})
}

// PriceIsNil applies the IsNil predicate on the "price" field.
func PriceIsNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldPrice)))
	})
}

// PriceNotNil applies the NotNil predicate on the "price" field.
func PriceNotNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldPrice)))
	})
}

// IndustryEQ applies the EQ predicate on the "industry" field.
func IndustryEQ(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldIndustry), v))
	})
}

// IndustryNEQ applies the NEQ predicate on the "industry" field.
func IndustryNEQ(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldIndustry), v))
	})
}

// IndustryIn applies the In predicate on the "industry" field.
func IndustryIn(vs ...string) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldIndustry), v...))
	})
}

// IndustryNotIn applies the NotIn predicate on the "industry" field.
func IndustryNotIn(vs ...string) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldIndustry), v...))
	})
}

// IndustryGT applies the GT predicate on the "industry" field.
func IndustryGT(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldIndustry), v))
	})
}

// IndustryGTE applies the GTE predicate on the "industry" field.
func IndustryGTE(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldIndustry), v))
	})
}

// IndustryLT applies the LT predicate on the "industry" field.
func IndustryLT(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldIndustry), v))
	})
}

// IndustryLTE applies the LTE predicate on the "industry" field.
func IndustryLTE(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldIndustry), v))
	})
}

// IndustryContains applies the Contains predicate on the "industry" field.
func IndustryContains(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldIndustry), v))
	})
}

// IndustryHasPrefix applies the HasPrefix predicate on the "industry" field.
func IndustryHasPrefix(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldIndustry), v))
	})
}

// IndustryHasSuffix applies the HasSuffix predicate on the "industry" field.
func IndustryHasSuffix(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldIndustry), v))
	})
}

// IndustryIsNil applies the IsNil predicate on the "industry" field.
func IndustryIsNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldIndustry)))
	})
}

// IndustryNotNil applies the NotNil predicate on the "industry" field.
func IndustryNotNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldIndustry)))
	})
}

// IndustryEqualFold applies the EqualFold predicate on the "industry" field.
func IndustryEqualFold(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldIndustry), v))
	})
}

// IndustryContainsFold applies the ContainsFold predicate on the "industry" field.
func IndustryContainsFold(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldIndustry), v))
	})
}

// MarketCarpEQ applies the EQ predicate on the "market_carp" field.
func MarketCarpEQ(v float64) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldMarketCarp), v))
	})
}

// MarketCarpNEQ applies the NEQ predicate on the "market_carp" field.
func MarketCarpNEQ(v float64) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldMarketCarp), v))
	})
}

// MarketCarpIn applies the In predicate on the "market_carp" field.
func MarketCarpIn(vs ...float64) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldMarketCarp), v...))
	})
}

// MarketCarpNotIn applies the NotIn predicate on the "market_carp" field.
func MarketCarpNotIn(vs ...float64) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldMarketCarp), v...))
	})
}

// MarketCarpGT applies the GT predicate on the "market_carp" field.
func MarketCarpGT(v float64) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldMarketCarp), v))
	})
}

// MarketCarpGTE applies the GTE predicate on the "market_carp" field.
func MarketCarpGTE(v float64) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldMarketCarp), v))
	})
}

// MarketCarpLT applies the LT predicate on the "market_carp" field.
func MarketCarpLT(v float64) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldMarketCarp), v))
	})
}

// MarketCarpLTE applies the LTE predicate on the "market_carp" field.
func MarketCarpLTE(v float64) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldMarketCarp), v))
	})
}

// MarketCarpIsNil applies the IsNil predicate on the "market_carp" field.
func MarketCarpIsNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldMarketCarp)))
	})
}

// MarketCarpNotNil applies the NotNil predicate on the "market_carp" field.
func MarketCarpNotNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldMarketCarp)))
	})
}

// LastDivEQ applies the EQ predicate on the "last_div" field.
func LastDivEQ(v float64) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLastDiv), v))
	})
}

// LastDivNEQ applies the NEQ predicate on the "last_div" field.
func LastDivNEQ(v float64) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldLastDiv), v))
	})
}

// LastDivIn applies the In predicate on the "last_div" field.
func LastDivIn(vs ...float64) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldLastDiv), v...))
	})
}

// LastDivNotIn applies the NotIn predicate on the "last_div" field.
func LastDivNotIn(vs ...float64) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldLastDiv), v...))
	})
}

// LastDivGT applies the GT predicate on the "last_div" field.
func LastDivGT(v float64) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldLastDiv), v))
	})
}

// LastDivGTE applies the GTE predicate on the "last_div" field.
func LastDivGTE(v float64) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldLastDiv), v))
	})
}

// LastDivLT applies the LT predicate on the "last_div" field.
func LastDivLT(v float64) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldLastDiv), v))
	})
}

// LastDivLTE applies the LTE predicate on the "last_div" field.
func LastDivLTE(v float64) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldLastDiv), v))
	})
}

// LastDivIsNil applies the IsNil predicate on the "last_div" field.
func LastDivIsNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldLastDiv)))
	})
}

// LastDivNotNil applies the NotNil predicate on the "last_div" field.
func LastDivNotNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldLastDiv)))
	})
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v float64) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDescription), v))
	})
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v float64) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldDescription), v))
	})
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...float64) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldDescription), v...))
	})
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...float64) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldDescription), v...))
	})
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v float64) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldDescription), v))
	})
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v float64) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldDescription), v))
	})
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v float64) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldDescription), v))
	})
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v float64) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldDescription), v))
	})
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldDescription)))
	})
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldDescription)))
	})
}

// WebsiteEQ applies the EQ predicate on the "website" field.
func WebsiteEQ(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldWebsite), v))
	})
}

// WebsiteNEQ applies the NEQ predicate on the "website" field.
func WebsiteNEQ(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldWebsite), v))
	})
}

// WebsiteIn applies the In predicate on the "website" field.
func WebsiteIn(vs ...string) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldWebsite), v...))
	})
}

// WebsiteNotIn applies the NotIn predicate on the "website" field.
func WebsiteNotIn(vs ...string) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldWebsite), v...))
	})
}

// WebsiteGT applies the GT predicate on the "website" field.
func WebsiteGT(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldWebsite), v))
	})
}

// WebsiteGTE applies the GTE predicate on the "website" field.
func WebsiteGTE(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldWebsite), v))
	})
}

// WebsiteLT applies the LT predicate on the "website" field.
func WebsiteLT(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldWebsite), v))
	})
}

// WebsiteLTE applies the LTE predicate on the "website" field.
func WebsiteLTE(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldWebsite), v))
	})
}

// WebsiteContains applies the Contains predicate on the "website" field.
func WebsiteContains(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldWebsite), v))
	})
}

// WebsiteHasPrefix applies the HasPrefix predicate on the "website" field.
func WebsiteHasPrefix(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldWebsite), v))
	})
}

// WebsiteHasSuffix applies the HasSuffix predicate on the "website" field.
func WebsiteHasSuffix(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldWebsite), v))
	})
}

// WebsiteIsNil applies the IsNil predicate on the "website" field.
func WebsiteIsNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldWebsite)))
	})
}

// WebsiteNotNil applies the NotNil predicate on the "website" field.
func WebsiteNotNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldWebsite)))
	})
}

// WebsiteEqualFold applies the EqualFold predicate on the "website" field.
func WebsiteEqualFold(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldWebsite), v))
	})
}

// WebsiteContainsFold applies the ContainsFold predicate on the "website" field.
func WebsiteContainsFold(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldWebsite), v))
	})
}

// CeoEQ applies the EQ predicate on the "ceo" field.
func CeoEQ(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCeo), v))
	})
}

// CeoNEQ applies the NEQ predicate on the "ceo" field.
func CeoNEQ(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCeo), v))
	})
}

// CeoIn applies the In predicate on the "ceo" field.
func CeoIn(vs ...string) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldCeo), v...))
	})
}

// CeoNotIn applies the NotIn predicate on the "ceo" field.
func CeoNotIn(vs ...string) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldCeo), v...))
	})
}

// CeoGT applies the GT predicate on the "ceo" field.
func CeoGT(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCeo), v))
	})
}

// CeoGTE applies the GTE predicate on the "ceo" field.
func CeoGTE(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCeo), v))
	})
}

// CeoLT applies the LT predicate on the "ceo" field.
func CeoLT(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCeo), v))
	})
}

// CeoLTE applies the LTE predicate on the "ceo" field.
func CeoLTE(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCeo), v))
	})
}

// CeoContains applies the Contains predicate on the "ceo" field.
func CeoContains(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldCeo), v))
	})
}

// CeoHasPrefix applies the HasPrefix predicate on the "ceo" field.
func CeoHasPrefix(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldCeo), v))
	})
}

// CeoHasSuffix applies the HasSuffix predicate on the "ceo" field.
func CeoHasSuffix(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldCeo), v))
	})
}

// CeoIsNil applies the IsNil predicate on the "ceo" field.
func CeoIsNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldCeo)))
	})
}

// CeoNotNil applies the NotNil predicate on the "ceo" field.
func CeoNotNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldCeo)))
	})
}

// CeoEqualFold applies the EqualFold predicate on the "ceo" field.
func CeoEqualFold(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldCeo), v))
	})
}

// CeoContainsFold applies the ContainsFold predicate on the "ceo" field.
func CeoContainsFold(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldCeo), v))
	})
}

// SectorEQ applies the EQ predicate on the "sector" field.
func SectorEQ(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSector), v))
	})
}

// SectorNEQ applies the NEQ predicate on the "sector" field.
func SectorNEQ(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSector), v))
	})
}

// SectorIn applies the In predicate on the "sector" field.
func SectorIn(vs ...string) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldSector), v...))
	})
}

// SectorNotIn applies the NotIn predicate on the "sector" field.
func SectorNotIn(vs ...string) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldSector), v...))
	})
}

// SectorGT applies the GT predicate on the "sector" field.
func SectorGT(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldSector), v))
	})
}

// SectorGTE applies the GTE predicate on the "sector" field.
func SectorGTE(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldSector), v))
	})
}

// SectorLT applies the LT predicate on the "sector" field.
func SectorLT(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldSector), v))
	})
}

// SectorLTE applies the LTE predicate on the "sector" field.
func SectorLTE(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldSector), v))
	})
}

// SectorContains applies the Contains predicate on the "sector" field.
func SectorContains(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldSector), v))
	})
}

// SectorHasPrefix applies the HasPrefix predicate on the "sector" field.
func SectorHasPrefix(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldSector), v))
	})
}

// SectorHasSuffix applies the HasSuffix predicate on the "sector" field.
func SectorHasSuffix(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldSector), v))
	})
}

// SectorIsNil applies the IsNil predicate on the "sector" field.
func SectorIsNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldSector)))
	})
}

// SectorNotNil applies the NotNil predicate on the "sector" field.
func SectorNotNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldSector)))
	})
}

// SectorEqualFold applies the EqualFold predicate on the "sector" field.
func SectorEqualFold(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldSector), v))
	})
}

// SectorContainsFold applies the ContainsFold predicate on the "sector" field.
func SectorContainsFold(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldSector), v))
	})
}

// CountryEQ applies the EQ predicate on the "country" field.
func CountryEQ(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCountry), v))
	})
}

// CountryNEQ applies the NEQ predicate on the "country" field.
func CountryNEQ(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCountry), v))
	})
}

// CountryIn applies the In predicate on the "country" field.
func CountryIn(vs ...string) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldCountry), v...))
	})
}

// CountryNotIn applies the NotIn predicate on the "country" field.
func CountryNotIn(vs ...string) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldCountry), v...))
	})
}

// CountryGT applies the GT predicate on the "country" field.
func CountryGT(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCountry), v))
	})
}

// CountryGTE applies the GTE predicate on the "country" field.
func CountryGTE(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCountry), v))
	})
}

// CountryLT applies the LT predicate on the "country" field.
func CountryLT(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCountry), v))
	})
}

// CountryLTE applies the LTE predicate on the "country" field.
func CountryLTE(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCountry), v))
	})
}

// CountryContains applies the Contains predicate on the "country" field.
func CountryContains(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldCountry), v))
	})
}

// CountryHasPrefix applies the HasPrefix predicate on the "country" field.
func CountryHasPrefix(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldCountry), v))
	})
}

// CountryHasSuffix applies the HasSuffix predicate on the "country" field.
func CountryHasSuffix(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldCountry), v))
	})
}

// CountryIsNil applies the IsNil predicate on the "country" field.
func CountryIsNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldCountry)))
	})
}

// CountryNotNil applies the NotNil predicate on the "country" field.
func CountryNotNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldCountry)))
	})
}

// CountryEqualFold applies the EqualFold predicate on the "country" field.
func CountryEqualFold(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldCountry), v))
	})
}

// CountryContainsFold applies the ContainsFold predicate on the "country" field.
func CountryContainsFold(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldCountry), v))
	})
}

// FullTimeEmployeesEQ applies the EQ predicate on the "full_time_employees" field.
func FullTimeEmployeesEQ(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldFullTimeEmployees), v))
	})
}

// FullTimeEmployeesNEQ applies the NEQ predicate on the "full_time_employees" field.
func FullTimeEmployeesNEQ(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldFullTimeEmployees), v))
	})
}

// FullTimeEmployeesIn applies the In predicate on the "full_time_employees" field.
func FullTimeEmployeesIn(vs ...string) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldFullTimeEmployees), v...))
	})
}

// FullTimeEmployeesNotIn applies the NotIn predicate on the "full_time_employees" field.
func FullTimeEmployeesNotIn(vs ...string) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldFullTimeEmployees), v...))
	})
}

// FullTimeEmployeesGT applies the GT predicate on the "full_time_employees" field.
func FullTimeEmployeesGT(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldFullTimeEmployees), v))
	})
}

// FullTimeEmployeesGTE applies the GTE predicate on the "full_time_employees" field.
func FullTimeEmployeesGTE(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldFullTimeEmployees), v))
	})
}

// FullTimeEmployeesLT applies the LT predicate on the "full_time_employees" field.
func FullTimeEmployeesLT(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldFullTimeEmployees), v))
	})
}

// FullTimeEmployeesLTE applies the LTE predicate on the "full_time_employees" field.
func FullTimeEmployeesLTE(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldFullTimeEmployees), v))
	})
}

// FullTimeEmployeesContains applies the Contains predicate on the "full_time_employees" field.
func FullTimeEmployeesContains(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldFullTimeEmployees), v))
	})
}

// FullTimeEmployeesHasPrefix applies the HasPrefix predicate on the "full_time_employees" field.
func FullTimeEmployeesHasPrefix(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldFullTimeEmployees), v))
	})
}

// FullTimeEmployeesHasSuffix applies the HasSuffix predicate on the "full_time_employees" field.
func FullTimeEmployeesHasSuffix(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldFullTimeEmployees), v))
	})
}

// FullTimeEmployeesIsNil applies the IsNil predicate on the "full_time_employees" field.
func FullTimeEmployeesIsNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldFullTimeEmployees)))
	})
}

// FullTimeEmployeesNotNil applies the NotNil predicate on the "full_time_employees" field.
func FullTimeEmployeesNotNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldFullTimeEmployees)))
	})
}

// FullTimeEmployeesEqualFold applies the EqualFold predicate on the "full_time_employees" field.
func FullTimeEmployeesEqualFold(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldFullTimeEmployees), v))
	})
}

// FullTimeEmployeesContainsFold applies the ContainsFold predicate on the "full_time_employees" field.
func FullTimeEmployeesContainsFold(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldFullTimeEmployees), v))
	})
}

// PhoneEQ applies the EQ predicate on the "phone" field.
func PhoneEQ(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPhone), v))
	})
}

// PhoneNEQ applies the NEQ predicate on the "phone" field.
func PhoneNEQ(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldPhone), v))
	})
}

// PhoneIn applies the In predicate on the "phone" field.
func PhoneIn(vs ...string) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldPhone), v...))
	})
}

// PhoneNotIn applies the NotIn predicate on the "phone" field.
func PhoneNotIn(vs ...string) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldPhone), v...))
	})
}

// PhoneGT applies the GT predicate on the "phone" field.
func PhoneGT(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldPhone), v))
	})
}

// PhoneGTE applies the GTE predicate on the "phone" field.
func PhoneGTE(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldPhone), v))
	})
}

// PhoneLT applies the LT predicate on the "phone" field.
func PhoneLT(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldPhone), v))
	})
}

// PhoneLTE applies the LTE predicate on the "phone" field.
func PhoneLTE(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldPhone), v))
	})
}

// PhoneContains applies the Contains predicate on the "phone" field.
func PhoneContains(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldPhone), v))
	})
}

// PhoneHasPrefix applies the HasPrefix predicate on the "phone" field.
func PhoneHasPrefix(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldPhone), v))
	})
}

// PhoneHasSuffix applies the HasSuffix predicate on the "phone" field.
func PhoneHasSuffix(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldPhone), v))
	})
}

// PhoneIsNil applies the IsNil predicate on the "phone" field.
func PhoneIsNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldPhone)))
	})
}

// PhoneNotNil applies the NotNil predicate on the "phone" field.
func PhoneNotNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldPhone)))
	})
}

// PhoneEqualFold applies the EqualFold predicate on the "phone" field.
func PhoneEqualFold(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldPhone), v))
	})
}

// PhoneContainsFold applies the ContainsFold predicate on the "phone" field.
func PhoneContainsFold(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldPhone), v))
	})
}

// AddressEQ applies the EQ predicate on the "address" field.
func AddressEQ(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldAddress), v))
	})
}

// AddressNEQ applies the NEQ predicate on the "address" field.
func AddressNEQ(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldAddress), v))
	})
}

// AddressIn applies the In predicate on the "address" field.
func AddressIn(vs ...string) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldAddress), v...))
	})
}

// AddressNotIn applies the NotIn predicate on the "address" field.
func AddressNotIn(vs ...string) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldAddress), v...))
	})
}

// AddressGT applies the GT predicate on the "address" field.
func AddressGT(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldAddress), v))
	})
}

// AddressGTE applies the GTE predicate on the "address" field.
func AddressGTE(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldAddress), v))
	})
}

// AddressLT applies the LT predicate on the "address" field.
func AddressLT(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldAddress), v))
	})
}

// AddressLTE applies the LTE predicate on the "address" field.
func AddressLTE(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldAddress), v))
	})
}

// AddressContains applies the Contains predicate on the "address" field.
func AddressContains(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldAddress), v))
	})
}

// AddressHasPrefix applies the HasPrefix predicate on the "address" field.
func AddressHasPrefix(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldAddress), v))
	})
}

// AddressHasSuffix applies the HasSuffix predicate on the "address" field.
func AddressHasSuffix(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldAddress), v))
	})
}

// AddressIsNil applies the IsNil predicate on the "address" field.
func AddressIsNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldAddress)))
	})
}

// AddressNotNil applies the NotNil predicate on the "address" field.
func AddressNotNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldAddress)))
	})
}

// AddressEqualFold applies the EqualFold predicate on the "address" field.
func AddressEqualFold(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldAddress), v))
	})
}

// AddressContainsFold applies the ContainsFold predicate on the "address" field.
func AddressContainsFold(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldAddress), v))
	})
}

// CityEQ applies the EQ predicate on the "city" field.
func CityEQ(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCity), v))
	})
}

// CityNEQ applies the NEQ predicate on the "city" field.
func CityNEQ(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCity), v))
	})
}

// CityIn applies the In predicate on the "city" field.
func CityIn(vs ...string) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldCity), v...))
	})
}

// CityNotIn applies the NotIn predicate on the "city" field.
func CityNotIn(vs ...string) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldCity), v...))
	})
}

// CityGT applies the GT predicate on the "city" field.
func CityGT(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCity), v))
	})
}

// CityGTE applies the GTE predicate on the "city" field.
func CityGTE(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCity), v))
	})
}

// CityLT applies the LT predicate on the "city" field.
func CityLT(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCity), v))
	})
}

// CityLTE applies the LTE predicate on the "city" field.
func CityLTE(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCity), v))
	})
}

// CityContains applies the Contains predicate on the "city" field.
func CityContains(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldCity), v))
	})
}

// CityHasPrefix applies the HasPrefix predicate on the "city" field.
func CityHasPrefix(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldCity), v))
	})
}

// CityHasSuffix applies the HasSuffix predicate on the "city" field.
func CityHasSuffix(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldCity), v))
	})
}

// CityIsNil applies the IsNil predicate on the "city" field.
func CityIsNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldCity)))
	})
}

// CityNotNil applies the NotNil predicate on the "city" field.
func CityNotNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldCity)))
	})
}

// CityEqualFold applies the EqualFold predicate on the "city" field.
func CityEqualFold(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldCity), v))
	})
}

// CityContainsFold applies the ContainsFold predicate on the "city" field.
func CityContainsFold(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldCity), v))
	})
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldState), v))
	})
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldState), v))
	})
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...string) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldState), v...))
	})
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...string) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldState), v...))
	})
}

// StateGT applies the GT predicate on the "state" field.
func StateGT(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldState), v))
	})
}

// StateGTE applies the GTE predicate on the "state" field.
func StateGTE(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldState), v))
	})
}

// StateLT applies the LT predicate on the "state" field.
func StateLT(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldState), v))
	})
}

// StateLTE applies the LTE predicate on the "state" field.
func StateLTE(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldState), v))
	})
}

// StateContains applies the Contains predicate on the "state" field.
func StateContains(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldState), v))
	})
}

// StateHasPrefix applies the HasPrefix predicate on the "state" field.
func StateHasPrefix(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldState), v))
	})
}

// StateHasSuffix applies the HasSuffix predicate on the "state" field.
func StateHasSuffix(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldState), v))
	})
}

// StateIsNil applies the IsNil predicate on the "state" field.
func StateIsNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldState)))
	})
}

// StateNotNil applies the NotNil predicate on the "state" field.
func StateNotNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldState)))
	})
}

// StateEqualFold applies the EqualFold predicate on the "state" field.
func StateEqualFold(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldState), v))
	})
}

// StateContainsFold applies the ContainsFold predicate on the "state" field.
func StateContainsFold(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldState), v))
	})
}

// ZipEQ applies the EQ predicate on the "zip" field.
func ZipEQ(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldZip), v))
	})
}

// ZipNEQ applies the NEQ predicate on the "zip" field.
func ZipNEQ(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldZip), v))
	})
}

// ZipIn applies the In predicate on the "zip" field.
func ZipIn(vs ...string) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldZip), v...))
	})
}

// ZipNotIn applies the NotIn predicate on the "zip" field.
func ZipNotIn(vs ...string) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldZip), v...))
	})
}

// ZipGT applies the GT predicate on the "zip" field.
func ZipGT(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldZip), v))
	})
}

// ZipGTE applies the GTE predicate on the "zip" field.
func ZipGTE(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldZip), v))
	})
}

// ZipLT applies the LT predicate on the "zip" field.
func ZipLT(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldZip), v))
	})
}

// ZipLTE applies the LTE predicate on the "zip" field.
func ZipLTE(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldZip), v))
	})
}

// ZipContains applies the Contains predicate on the "zip" field.
func ZipContains(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldZip), v))
	})
}

// ZipHasPrefix applies the HasPrefix predicate on the "zip" field.
func ZipHasPrefix(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldZip), v))
	})
}

// ZipHasSuffix applies the HasSuffix predicate on the "zip" field.
func ZipHasSuffix(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldZip), v))
	})
}

// ZipIsNil applies the IsNil predicate on the "zip" field.
func ZipIsNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldZip)))
	})
}

// ZipNotNil applies the NotNil predicate on the "zip" field.
func ZipNotNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldZip)))
	})
}

// ZipEqualFold applies the EqualFold predicate on the "zip" field.
func ZipEqualFold(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldZip), v))
	})
}

// ZipContainsFold applies the ContainsFold predicate on the "zip" field.
func ZipContainsFold(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldZip), v))
	})
}

// ImageEQ applies the EQ predicate on the "image" field.
func ImageEQ(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldImage), v))
	})
}

// ImageNEQ applies the NEQ predicate on the "image" field.
func ImageNEQ(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldImage), v))
	})
}

// ImageIn applies the In predicate on the "image" field.
func ImageIn(vs ...string) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldImage), v...))
	})
}

// ImageNotIn applies the NotIn predicate on the "image" field.
func ImageNotIn(vs ...string) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldImage), v...))
	})
}

// ImageGT applies the GT predicate on the "image" field.
func ImageGT(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldImage), v))
	})
}

// ImageGTE applies the GTE predicate on the "image" field.
func ImageGTE(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldImage), v))
	})
}

// ImageLT applies the LT predicate on the "image" field.
func ImageLT(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldImage), v))
	})
}

// ImageLTE applies the LTE predicate on the "image" field.
func ImageLTE(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldImage), v))
	})
}

// ImageContains applies the Contains predicate on the "image" field.
func ImageContains(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldImage), v))
	})
}

// ImageHasPrefix applies the HasPrefix predicate on the "image" field.
func ImageHasPrefix(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldImage), v))
	})
}

// ImageHasSuffix applies the HasSuffix predicate on the "image" field.
func ImageHasSuffix(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldImage), v))
	})
}

// ImageIsNil applies the IsNil predicate on the "image" field.
func ImageIsNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldImage)))
	})
}

// ImageNotNil applies the NotNil predicate on the "image" field.
func ImageNotNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldImage)))
	})
}

// ImageEqualFold applies the EqualFold predicate on the "image" field.
func ImageEqualFold(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldImage), v))
	})
}

// ImageContainsFold applies the ContainsFold predicate on the "image" field.
func ImageContainsFold(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldImage), v))
	})
}

// IpoDateEQ applies the EQ predicate on the "ipo_date" field.
func IpoDateEQ(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldIpoDate), v))
	})
}

// IpoDateNEQ applies the NEQ predicate on the "ipo_date" field.
func IpoDateNEQ(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldIpoDate), v))
	})
}

// IpoDateIn applies the In predicate on the "ipo_date" field.
func IpoDateIn(vs ...string) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldIpoDate), v...))
	})
}

// IpoDateNotIn applies the NotIn predicate on the "ipo_date" field.
func IpoDateNotIn(vs ...string) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldIpoDate), v...))
	})
}

// IpoDateGT applies the GT predicate on the "ipo_date" field.
func IpoDateGT(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldIpoDate), v))
	})
}

// IpoDateGTE applies the GTE predicate on the "ipo_date" field.
func IpoDateGTE(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldIpoDate), v))
	})
}

// IpoDateLT applies the LT predicate on the "ipo_date" field.
func IpoDateLT(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldIpoDate), v))
	})
}

// IpoDateLTE applies the LTE predicate on the "ipo_date" field.
func IpoDateLTE(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldIpoDate), v))
	})
}

// IpoDateContains applies the Contains predicate on the "ipo_date" field.
func IpoDateContains(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldIpoDate), v))
	})
}

// IpoDateHasPrefix applies the HasPrefix predicate on the "ipo_date" field.
func IpoDateHasPrefix(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldIpoDate), v))
	})
}

// IpoDateHasSuffix applies the HasSuffix predicate on the "ipo_date" field.
func IpoDateHasSuffix(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldIpoDate), v))
	})
}

// IpoDateIsNil applies the IsNil predicate on the "ipo_date" field.
func IpoDateIsNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldIpoDate)))
	})
}

// IpoDateNotNil applies the NotNil predicate on the "ipo_date" field.
func IpoDateNotNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldIpoDate)))
	})
}

// IpoDateEqualFold applies the EqualFold predicate on the "ipo_date" field.
func IpoDateEqualFold(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldIpoDate), v))
	})
}

// IpoDateContainsFold applies the ContainsFold predicate on the "ipo_date" field.
func IpoDateContainsFold(v string) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldIpoDate), v))
	})
}

// YieldEQ applies the EQ predicate on the "yield" field.
func YieldEQ(v float64) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldYield), v))
	})
}

// YieldNEQ applies the NEQ predicate on the "yield" field.
func YieldNEQ(v float64) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldYield), v))
	})
}

// YieldIn applies the In predicate on the "yield" field.
func YieldIn(vs ...float64) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldYield), v...))
	})
}

// YieldNotIn applies the NotIn predicate on the "yield" field.
func YieldNotIn(vs ...float64) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldYield), v...))
	})
}

// YieldGT applies the GT predicate on the "yield" field.
func YieldGT(v float64) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldYield), v))
	})
}

// YieldGTE applies the GTE predicate on the "yield" field.
func YieldGTE(v float64) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldYield), v))
	})
}

// YieldLT applies the LT predicate on the "yield" field.
func YieldLT(v float64) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldYield), v))
	})
}

// YieldLTE applies the LTE predicate on the "yield" field.
func YieldLTE(v float64) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldYield), v))
	})
}

// YieldIsNil applies the IsNil predicate on the "yield" field.
func YieldIsNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldYield)))
	})
}

// YieldNotNil applies the NotNil predicate on the "yield" field.
func YieldNotNil() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldYield)))
	})
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Stocks {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Stocks(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldUpdatedAt), v))
	})
}

// HasStocks applies the HasEdge predicate on the "stocks" edge.
func HasStocks() predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(StocksTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, StocksTable, StocksPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStocksWith applies the HasEdge predicate on the "stocks" edge with a given conditions (other predicates).
func HasStocksWith(preds ...predicate.Stocks) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, StocksTable, StocksPrimaryKey...),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Stocks) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Stocks) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Stocks) predicate.Stocks {
	return predicate.Stocks(func(s *sql.Selector) {
		p(s.Not())
	})
}
